//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class C__RefactorLog
{
    public System.Guid OperationKey { get; set; }
}

public partial class Department
{
    public int DepartmentID { get; set; }
    public string DepartmentName { get; set; }
    public string HR { get; set; }
    public string IT { get; set; }
}

public partial class Employee
{
    public int ID { get; set; }
    public string Name { get; set; }
    public System.DateTime HireDate { get; set; }
    public int Salary { get; set; }
    public int DepartmentID { get; set; }
    public string Address { get; set; }
}
